//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrieve_net_II.R.Configurations {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Retrieve : global::System.Configuration.ApplicationSettingsBase {
        
        private static Retrieve defaultInstance = ((Retrieve)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Retrieve())));
        
        public static Retrieve Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LibraryLocation {
            get {
                return ((string)(this["LibraryLocation"]));
            }
            set {
                this["LibraryLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int SearchResultLimit {
            get {
                return ((int)(this["SearchResultLimit"]));
            }
            set {
                this["SearchResultLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDevelopmentServer {
            get {
                return ((bool)(this["UseDevelopmentServer"]));
            }
            set {
                this["UseDevelopmentServer"] = value;
            }
        }
    }
}
